service: first-api

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.get_item
    events:
      - httpApi:
          method: GET
          path: /api/v1/items
  item_colour:
    handler: item_colour.handler
    events:
      - httpApi:
          method: GET
          path: /api/v1/itemColour